
  var res = {
    world_tilemap_tmx_greyscale : "res/tmx-equal-greyscale.tmx",
    world_tilemap_tmx_colour : "res/tmx-equal-colour.tmx",
    world_tilemap_background : "res/background-equal-greyscale.png",
    world_tilemap_foreground : "res/foreground-equal-greyscale.png",
    dot_png : "res/images/dot.png",
    fire_texture: "res/images/fire.png",
    policy_dot_off_png : "res/images/BUTTONS/DOT_OFF.png",
    policy_dot_on_png : "res/images/niab/DOT_ON.png",
    quit_off_png : "res/images/niab/BUTTON_QUIT.png",
    quit_on_png : "res/images/niab/BUTTON_QUIT.png",
    options_off_png : "res/images/niab/BUTTON_OPTIONS_OFF.png",
    options_on_png : "res/images/niab/BUTTON_OPTIONS_ON.png",
    pause_off_png : "res/images/niab/BUTTON_PAUSE_NORMAL.png",
    pause_on_png : "res/images/niab/BUTTON_PAUSE_ON.png",
    play_off_png : "res/images/niab/BUTTON_PLAY_NORMAL.png",
    play_on_png : "res/images/niab/BUTTON_PLAY_ON.png",
    playfast_off_png : "res/images/niab/BUTTON_PLAYFAST_NORMAL.png",
    playfast_on_png : "res/images/niab/BUTTON_PLAYFAST_ON.png",
    antarctica_small_png : "res/images/NEW_ICONS/ANTARCTICA_SMALL.png",
    antarctica_large_png : "res/images/NEW_ICONS/ANTARCTICA_LARGE.png",
    resource_icon: "res/images/NEW_ICONS/ICON_RESOURCE.png",
    resource_economy_1: "res/images/niab/ICON_RESOURCE_ECONOMY_1.png",
    resource_economy_2: "res/images/niab/ICON_RESOURCE_ECONOMY_2.png",
    resource_economy_3: "res/images/niab/ICON_RESOURCE_ECONOMY_3.png",
    resource_economy_4: "res/images/niab/ICON_RESOURCE_ECONOMY_4.png",
    resource_politics_1: "res/images/niab/ICON_RESOURCE_POLITICS_1.png",
    resource_politics_2: "res/images/niab/ICON_RESOURCE_POLITICS_2.png",
    resource_politics_3: "res/images/niab/ICON_RESOURCE_POLITICS_3.png",
    resource_politics_4: "res/images/niab/ICON_RESOURCE_POLITICS_4.png",
    resource_culture_1: "res/images/niab/ICON_RESOURCE_CULTURE_1.png",
    resource_culture_2: "res/images/niab/ICON_RESOURCE_CULTURE_2.png",
    resource_culture_3: "res/images/niab/ICON_RESOURCE_CULTURE_3.png",
    resource_culture_4: "res/images/niab/ICON_RESOURCE_CULTURE_4.png",
    resource_ecology_1: "res/images/niab/ICON_RESOURCE_ECOLOGY_1.png",
    resource_ecology_2: "res/images/niab/ICON_RESOURCE_ECOLOGY_2.png",
    resource_ecology_3: "res/images/niab/ICON_RESOURCE_ECOLOGY_3.png",
    resource_ecology_4: "res/images/niab/ICON_RESOURCE_ECOLOGY_4.png",
    button_white: "res/images/BUTTONS/BUTTON_WHITE.png",
    button_grey: "res/images/BUTTONS/BUTTON_GREY.png",
    progress_bar: "res/images/progress-bar.png",
    ctrls_background: "res/images/ctrls-background.png",
    status_button: "res/images/status-button.png",
    shader_outline_vertex: "res/shaders/mask_country.vsh",
    shader_outline_fragment: "res/shaders/mask_country.fsh",
    ArvoFont : {
      type:"font",
      name:"ArvoFont",
      srcs:["res/fonts/Arvo-Regular.ttf", "res/fonts/Arvo-Regular.ttf"]
    },
    JosefinSansFont : {
      type:"font",
      name:"JosefinSansFont",
      srcs:["res/fonts/JosefinSans-Regular.ttf", "res/fonts/JosefinSans-Regular.ttf"]
    },
  FJI_png:"res/countries/FJI_equal.png",
TZA_png:"res/countries/TZA_equal.png",
ESH_png:"res/countries/ESH_equal.png",
CAN_png:"res/countries/CAN_equal.png",
USA_png:"res/countries/USA_equal.png",
PNG_png:"res/countries/PNG_equal.png",
IDN_png:"res/countries/IDN_equal.png",
ARG_png:"res/countries/ARG_equal.png",
CHL_png:"res/countries/CHL_equal.png",
COD_png:"res/countries/COD_equal.png",
SOM_png:"res/countries/SOM_equal.png",
KEN_png:"res/countries/KEN_equal.png",
SDN_png:"res/countries/SDN_equal.png",
TCD_png:"res/countries/TCD_equal.png",
HTI_png:"res/countries/HTI_equal.png",
DOM_png:"res/countries/DOM_equal.png",
RUS_png:"res/countries/RUS_equal.png",
FLK_png:"res/countries/FLK_equal.png",
NOR_png:"res/countries/NOR_equal.png",
GRL_png:"res/countries/GRL_equal.png",
LSO_png:"res/countries/LSO_equal.png",
MEX_png:"res/countries/MEX_equal.png",
URY_png:"res/countries/URY_equal.png",
BRA_png:"res/countries/BRA_equal.png",
BOL_png:"res/countries/BOL_equal.png",
PER_png:"res/countries/PER_equal.png",
COL_png:"res/countries/COL_equal.png",
PAN_png:"res/countries/PAN_equal.png",
CRI_png:"res/countries/CRI_equal.png",
NIC_png:"res/countries/NIC_equal.png",
HND_png:"res/countries/HND_equal.png",
SLV_png:"res/countries/SLV_equal.png",
GTM_png:"res/countries/GTM_equal.png",
BLZ_png:"res/countries/BLZ_equal.png",
VEN_png:"res/countries/VEN_equal.png",
GUY_png:"res/countries/GUY_equal.png",
SUR_png:"res/countries/SUR_equal.png",
FRA_png:"res/countries/FRA_equal.png",
ECU_png:"res/countries/ECU_equal.png",
CUB_png:"res/countries/CUB_equal.png",
ZWE_png:"res/countries/ZWE_equal.png",
BWA_png:"res/countries/BWA_equal.png",
NAM_png:"res/countries/NAM_equal.png",
SEN_png:"res/countries/SEN_equal.png",
MLI_png:"res/countries/MLI_equal.png",
MRT_png:"res/countries/MRT_equal.png",
BEN_png:"res/countries/BEN_equal.png",
NER_png:"res/countries/NER_equal.png",
NGA_png:"res/countries/NGA_equal.png",
CMR_png:"res/countries/CMR_equal.png",
TGO_png:"res/countries/TGO_equal.png",
GHA_png:"res/countries/GHA_equal.png",
CIV_png:"res/countries/CIV_equal.png",
GIN_png:"res/countries/GIN_equal.png",
GNB_png:"res/countries/GNB_equal.png",
LBR_png:"res/countries/LBR_equal.png",
SLE_png:"res/countries/SLE_equal.png",
BFA_png:"res/countries/BFA_equal.png",
CAF_png:"res/countries/CAF_equal.png",
COG_png:"res/countries/COG_equal.png",
GAB_png:"res/countries/GAB_equal.png",
ZMB_png:"res/countries/ZMB_equal.png",
MWI_png:"res/countries/MWI_equal.png",
MOZ_png:"res/countries/MOZ_equal.png",
SWZ_png:"res/countries/SWZ_equal.png",
AGO_png:"res/countries/AGO_equal.png",
BDI_png:"res/countries/BDI_equal.png",
ISR_png:"res/countries/ISR_equal.png",
MDG_png:"res/countries/MDG_equal.png",
GMB_png:"res/countries/GMB_equal.png",
TUN_png:"res/countries/TUN_equal.png",
DZA_png:"res/countries/DZA_equal.png",
JOR_png:"res/countries/JOR_equal.png",
ARE_png:"res/countries/ARE_equal.png",
KWT_png:"res/countries/KWT_equal.png",
IRQ_png:"res/countries/IRQ_equal.png",
OMN_png:"res/countries/OMN_equal.png",
KHM_png:"res/countries/KHM_equal.png",
THA_png:"res/countries/THA_equal.png",
LAO_png:"res/countries/LAO_equal.png",
MMR_png:"res/countries/MMR_equal.png",
VNM_png:"res/countries/VNM_equal.png",
PRK_png:"res/countries/PRK_equal.png",
KOR_png:"res/countries/KOR_equal.png",
MNG_png:"res/countries/MNG_equal.png",
IND_png:"res/countries/IND_equal.png",
BGD_png:"res/countries/BGD_equal.png",
BTN_png:"res/countries/BTN_equal.png",
NPL_png:"res/countries/NPL_equal.png",
PAK_png:"res/countries/PAK_equal.png",
AFG_png:"res/countries/AFG_equal.png",
TJK_png:"res/countries/TJK_equal.png",
KGZ_png:"res/countries/KGZ_equal.png",
SYR_png:"res/countries/SYR_equal.png",
ARM_png:"res/countries/ARM_equal.png",
SWE_png:"res/countries/SWE_equal.png",
BLR_png:"res/countries/BLR_equal.png",
UKR_png:"res/countries/UKR_equal.png",
POL_png:"res/countries/POL_equal.png",
AUT_png:"res/countries/AUT_equal.png",
HUN_png:"res/countries/HUN_equal.png",
MDA_png:"res/countries/MDA_equal.png",
ROU_png:"res/countries/ROU_equal.png",
LTU_png:"res/countries/LTU_equal.png",
LVA_png:"res/countries/LVA_equal.png",
EST_png:"res/countries/EST_equal.png",
DEU_png:"res/countries/DEU_equal.png",
BGR_png:"res/countries/BGR_equal.png",
GRC_png:"res/countries/GRC_equal.png",
TUR_png:"res/countries/TUR_equal.png",
ALB_png:"res/countries/ALB_equal.png",
HRV_png:"res/countries/HRV_equal.png",
CHE_png:"res/countries/CHE_equal.png",
BEL_png:"res/countries/BEL_equal.png",
NLD_png:"res/countries/NLD_equal.png",
PRT_png:"res/countries/PRT_equal.png",
ESP_png:"res/countries/ESP_equal.png",
IRL_png:"res/countries/IRL_equal.png",
NCL_png:"res/countries/NCL_equal.png",
NZL_png:"res/countries/NZL_equal.png",
AUS_png:"res/countries/AUS_equal.png",
LKA_png:"res/countries/LKA_equal.png",
CHN_png:"res/countries/CHN_equal.png",
TWN_png:"res/countries/TWN_equal.png",
ITA_png:"res/countries/ITA_equal.png",
DNK_png:"res/countries/DNK_equal.png",
GBR_png:"res/countries/GBR_equal.png",
ISL_png:"res/countries/ISL_equal.png",
AZE_png:"res/countries/AZE_equal.png",
GEO_png:"res/countries/GEO_equal.png",
PHL_png:"res/countries/PHL_equal.png",
MYS_png:"res/countries/MYS_equal.png",
SVN_png:"res/countries/SVN_equal.png",
FIN_png:"res/countries/FIN_equal.png",
SVK_png:"res/countries/SVK_equal.png",
CZE_png:"res/countries/CZE_equal.png",
ERI_png:"res/countries/ERI_equal.png",
JPN_png:"res/countries/JPN_equal.png",
PRY_png:"res/countries/PRY_equal.png",
YEM_png:"res/countries/YEM_equal.png",
SAU_png:"res/countries/SAU_equal.png",
ATA_png:"res/countries/ATA_equal.png",
MAR_png:"res/countries/MAR_equal.png",
EGY_png:"res/countries/EGY_equal.png",
LBY_png:"res/countries/LBY_equal.png",
ETH_png:"res/countries/ETH_equal.png",
DJI_png:"res/countries/DJI_equal.png",
UGA_png:"res/countries/UGA_equal.png",
RWA_png:"res/countries/RWA_equal.png",
BIH_png:"res/countries/BIH_equal.png",
MKD_png:"res/countries/MKD_equal.png",
SRB_png:"res/countries/SRB_equal.png",
MNE_png:"res/countries/MNE_equal.png",
KOS_png:"res/countries/KOS_equal.png",
SSD_png:"res/countries/SSD_equal.png",

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
